### ISSUE TITLE
Double ep_train_epoch functions in base function.py

### ISSUE THREAD

**Issue by fugaweiren** [Louise-X10/CS5562-HW2#1]
Hi! There are 2 copies of ep_train_epoch at "base function.py:Line75" and "base function.py:Line75" and "base function.py:Line141". Sorry for posting it here. The announcement on Canvas is not out yet so I can't reply there.

**Comment by Louise-X10** [comment]
Thanks! The duplicate has been removed. Please use the function on Line 141.
